package org.signserver.clientws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.4
 * 2021-08-19T15:50:36.962+07:00
 * Generated source version: 3.4.4
 *
 */
@WebService(targetNamespace = "http://clientws.signserver.org/", name = "ClientWS")
@XmlSeeAlso({ObjectFactory.class})
public interface ClientWS {

    @WebMethod
    @RequestWrapper(localName = "processSOD", targetNamespace = "http://clientws.signserver.org/", className = "org.signserver.clientws.ProcessSOD")
    @ResponseWrapper(localName = "processSODResponse", targetNamespace = "http://clientws.signserver.org/", className = "org.signserver.clientws.ProcessSODResponse")
    @WebResult(name = "return", targetNamespace = "")
    public org.signserver.clientws.SodResponse processSOD(

        @WebParam(name = "worker", targetNamespace = "")
        java.lang.String worker,
        @WebParam(name = "metadata", targetNamespace = "")
        java.util.List<org.signserver.clientws.Metadata> metadata,
        @WebParam(name = "sodData", targetNamespace = "")
        org.signserver.clientws.SodRequest sodData
    ) throws RequestFailedException_Exception, InternalServerException_Exception;

    @WebMethod
    @RequestWrapper(localName = "processData", targetNamespace = "http://clientws.signserver.org/", className = "org.signserver.clientws.ProcessData")
    @ResponseWrapper(localName = "processDataResponse", targetNamespace = "http://clientws.signserver.org/", className = "org.signserver.clientws.ProcessDataResponse")
    @WebResult(name = "return", targetNamespace = "")
    public org.signserver.clientws.DataResponse processData(

        @WebParam(name = "worker", targetNamespace = "")
        java.lang.String worker,
        @WebParam(name = "metadata", targetNamespace = "")
        java.util.List<org.signserver.clientws.Metadata> metadata,
        @WebParam(name = "data", targetNamespace = "")
        byte[] data
    ) throws RequestFailedException_Exception, InternalServerException_Exception;
}
