
package org.signserver.clientws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.4.4
 * 2021-08-19T15:50:36.910+07:00
 * Generated source version: 3.4.4
 */

@WebFault(name = "RequestFailedException", targetNamespace = "http://clientws.signserver.org/")
public class RequestFailedException_Exception extends Exception {

    private org.signserver.clientws.RequestFailedException faultInfo;

    public RequestFailedException_Exception() {
        super();
    }

    public RequestFailedException_Exception(String message) {
        super(message);
    }

    public RequestFailedException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public RequestFailedException_Exception(String message, org.signserver.clientws.RequestFailedException requestFailedException) {
        super(message);
        this.faultInfo = requestFailedException;
    }

    public RequestFailedException_Exception(String message, org.signserver.clientws.RequestFailedException requestFailedException, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = requestFailedException;
    }

    public org.signserver.clientws.RequestFailedException getFaultInfo() {
        return this.faultInfo;
    }
}
